### ISSUE TITLE
No scrolldown bar in Modern View

### ISSUE THREAD

**Issue by Kapitan2015** [tom-daly/spfx-global-navigation#14]
In SharePoint Online, specifically in modern view, I have a menu in which the amount of items exceeds the height of the page. There is no way to scroll down to see the list items in the menu, there is no option to do so.
In the classic view, there is no problem to allow scroll down and see all the menu items. Is there any change we can make to allow scrolldown?
![No scrolldown Manu in Modern View](https://user-images.githubusercontent.com/14790578/99727171-91cbc680-2a85-11eb-85cb-623cdcbf9396.png)

**Comment by tom-daly** [comment]
that's is a lot of nav nodes, i'll check to see if there is anything that can be done here.

**Comment by tom-daly** [comment]
I don't believe I can support that case. I've tried to add a scroll to the fly out but if you have a 3rd level it will break that. The issue seems to be that the scrolling window is limited to the content and the overflow is not picked up.

if I set the overflow-y on the #spPageChromeAppDiv element, the page will scroll to fit the nav but the content stays the size of the window. 

![image](https://user-images.githubusercontent.com/9259305/100387694-b7f9e500-2ff6-11eb-86fd-ab0c75efca26.png)

**Comment by Kapitan2015** [comment]
Thanks Tom for the pointers! We fixed adding this to  globalNavStyles.scss:
`//Scroll down in modern view
.sp-App-bodyMain{
  overflow-y: scroll;
}
.spAppAndPropertyPanelContainer{
  overflow-y: scroll;
}`

Still, after the third submenu it can give issues, but with less submenus it works.
