### ISSUE TITLE
Item limit

### ISSUE THREAD

**Issue by snakebte75** [tom-daly/spfx-global-navigation#4]
I've been using this solution for a couple months now and I love it, but after adding some more links to my navigation list today I noticed that the menu stopped displaying all of my menus. It seems to only pull the first ~100 items in the list and drop everything after that. Is there a way around this limit? 

Also, has the project been updated to run with Node.js 10 yet? I'd like to update, from version 8 but compiling this requires 8.

**Comment by tom-daly** [comment]
Thanks so much for the feedback. I just pushed the update today so that it compiles with node 10.. the issue is in the spfx-versioning.js file

fs.writeFile ---> fs.writeFileSync

As per the second issue the default rest call only returns 100 items, If you want quick you can update the query to get all the items to .top(2000) or something higher than 100. 

![image](https://user-images.githubusercontent.com/9259305/71210799-b74fbf00-227b-11ea-8651-af6034dac6b6.png)

**Comment by tom-daly** [comment]
I'm going to verify that is the only hold up. I am going to upgrade the project to SPFX v1.9.x tonight and let you know if once it's successfully built.

**Comment by snakebte75** [comment]
Thanks for the fix to the item limit. I wasn't able to compile with Node.js 10, but it still runs fine in Node.js 8.

**Comment by tom-daly** [comment]
I think i see the issue. this is on spfx v1.7 libraries. I am going to upgrade the project and let you know once I have the build working as it should.

**Comment by tom-daly** [comment]
updated project to spfx v1.9.1 and verified it builds in node 10. get the latest version and delete node_modules.

**Comment by snakebte75** [comment]
Recompiled with the updates this morning and it is running great! Thanks for your help.
